apiVersion: v1
kind: Service
metadata:
  name: connessioni-service
  namespace: asw-project
spec:
  selector:
    app: instagnam
    service: connessioni
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  
