apiVersion: v1
kind: Service
metadata:
  name: zoo1-service
  namespace: asw-project
spec:
  selector:
    app: instagnam
    service: zookeeper
  ports:
  - name: client
    protocol: TCP
    port: 2181
  - name: follower
    protocol: TCP
    port: 2888
  - name: leader
    protocol: TCP
    port: 3888
    

