kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-ricette-pv-volume
  namespace: asw-project
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-ricette-pv-claim
  namespace: asw-project
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi