apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-ricette-pv-volume
  namespace: asw-project
  labels:
    type: local
    app: instagnam
    service: postgres-ricette
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ricette-pv-claim
  namespace: asw-project
  labels:
    app: instagnam
    service: postgres-connessioni
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

