kind: PersistentVolume
apiVersion: v1
metadata:
  name: connessioni-pv-volume
  namespace: asw-project
  labels:
    app: instagnam
    service: postgres-connessioni
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: connessioni-pv-claim
  namespace: asw-project
  labels:
    app: instagnam
    service: postgres-connessioni
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
