apiVersion: v1
kind: Service
metadata:
  name: postgres-ricette-seguite-service
  namespace: asw-project
spec:
  type: NodePort
  selector:
    app: instagnam
    service: postgres-ricette-seguite
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432