apiVersion: v1
kind: Service
metadata:
  name: ricette-seguite-service
  namespace: asw-project
spec:
  selector:
    app: instagnam
    service: ricette-seguite
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  
